// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// main_UStatsPvalueMain
double main_UStatsPvalueMain(double NoKernel, double pobs, arma::mat CovVarAll, double SimNumber);
RcppExport SEXP _KMU_main_UStatsPvalueMain(SEXP NoKernelSEXP, SEXP pobsSEXP, SEXP CovVarAllSEXP, SEXP SimNumberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type NoKernel(NoKernelSEXP);
    Rcpp::traits::input_parameter< double >::type pobs(pobsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type CovVarAll(CovVarAllSEXP);
    Rcpp::traits::input_parameter< double >::type SimNumber(SimNumberSEXP);
    rcpp_result_gen = Rcpp::wrap(main_UStatsPvalueMain(NoKernel, pobs, CovVarAll, SimNumber));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_KMU_main_UStatsPvalueMain", (DL_FUNC) &_KMU_main_UStatsPvalueMain, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_KMU(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
