# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

main_UStatsPvalueMain <- function(NoKernel, pobs, CovVarAll, SimNumber) {
    .Call(`_KMU_main_UStatsPvalueMain`, NoKernel, pobs, CovVarAll, SimNumber)
}

